#-------------------------------
# General Site Settings

title: Josh and Jenn's Wedding
description: September 5th 2015 // 16:00 // Arnos Vale Cemetery Bristol
email: jen@mysociety.org
google: https://docs.google.com/a/mysociety.org/forms/d/1sE1BXqt05rpiuipIHdNrFrQEYAj4845LFRn5LrVplgo/viewform

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: about, url: '#about'}
- {name: important, url: '#important'}
- {name: reception, url: '#reception'}
- {name: rsvp, url: '#rsvp'}
- {name: directions, url: '#directions'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Josh and Jenns Wedding September 2015'

#-------------------------------
# about Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
     <p>
       <strong>
         Josh and Jenn are getting married on Saturday September 5th 2015 at
         4pm in the Underwood Centre at Arnos Vale Cemetery, Bristol.
        </strong>
     </p>
     The [Underwood Centre](http://www.arnosvale.org.uk/weddings) is a woodland
     venue and the ceremony and pre-wedding breakfast drinks will be held here,
     so sensible shoes are advised (especially as the path to the venue is
     steep and cobbled).

#-------------------------------
# important Section

blurb2: >
      Some important information for those attending the ceremony or reception. Please scroll through!
information: 
   - {name: 'Parking',
      quote: <p><strong>There is very limited parking at the venue.</strong> The nearest train station is Temple Meads located just under a mile east of the site. Taxis are available from outside Temple Meads station. Bus services 1 X39 57 178 and 349 stop outside the Bath Road gates. These are the best ways to get to the venue.</p>,
      logo: 'parking.jpg',
      }
   - {name: 'Invitees Only',
      quote: <p><strong>We have limited numbers at the ceremony and reception.</strong> We want to have an small intimate celebration and we had to be creative in making sure that we can fit everyone in our venue. There really is no room for unexpected extras. So please only the people whose names appear on the invite envelope are asked to RSVP. Sorry.</p>,
      logo: 'rsvp.jpg',
      }
   - {name: 'Food',
      quote: <p><strong>Ceremony guests will be fed!</strong> We will be having mezze and tagines served in the Spielman Centre at 1830. Since the ceremony starts at 1600 we suggest you have lunch beforehand. There are a number of great restaurants in Bristol so let us know if you need recommendations.</p>,
      logo: 'food.jpg',
      }
   - {name: 'Dress Code',
      quote: <p><strong>We have no strict opinions. We just want you to be comfortable and have a good time</strong>. Some recommendations though; As the ceremony is outside and english weather is unpredictable we'd suggest you bring an umbrella or and maybe a light jacket. There are some steep paths around the Cemetery so high heels really wouldn't be recommended. </p>,
      logo: 'dreescode.jpg',
      }
   - {name: 'Gifts',
      quote: <p><strong>We don't need presents we just want you presence</strong> however if you want to give a gift please make a donation to our honeymoon fund!</p>,
      logo: 'gifts.jpg',
      }
#------------------------------- # Reception Section

blurb3: > 
        <p>
        The reception will be held at the Spielman Centre at Arnos Vale Cemetery in Bristol from 2030
        onwards. There will be no food served at the reception (apart from cake) and the bar is a paid bar! We have
        to leave Arnos Vale Cemetery at 2300 on the dot but we will be continuing the party, for those who wish to stay out, at Mr Wolf's in the centre of Bristol.
        </p>
        Please arrive dead on 2030 if you want to join in the speeches and toasts.

#-------------------------------
# rsvp Section

blurb4: > 
 We'd like you to RSVP online so we can collect other data we need (food allergies, accomodation needs etc)

#-------------------------------
# Directions Section



